// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrdyvbeaferrnthoguaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZHl2YmVhZmVycm50aG9ndWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODY2NjgsImV4cCI6MjA3MDQ2MjY2OH0.vGsS1Sffgix-iLifOOsYA1A1IDb1mLUwdbfGez6qH0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});